S3_BUCKET:=app
ACCOUNT_ID:=408393949eb505f73a9af86454446f19
# 默认目标
all: build

# 构建目标
build:
	GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o ./bin/pinterest_linux
	GOOS=darwin GOARCH=amd64 go build  -ldflags="-s -w" -o ./bin/pinterest
	GOOS=windows GOARCH=amd64 go build  -ldflags="-s -w" -o ./bin/pinterest.exe

upload:
#http://app.parap.us.kg/h2s3upload:
	aws s3 sync ./bin s3://$(S3_BUCKET)/pinterest --region auto --endpoint-url https://$(ACCOUNT_ID).r2.cloudflarestorage.com